import { EventObject } from "./EventObject";
import { IPickerItem } from "./pickeritems/IPickerItem";
import { ISearchPickerOptions } from "./options/ISearchPickerOptions";
export declare class SearchPickerChoices extends EventObject {
    private container;
    private options;
    private inputElm;
    private inputJsElmWrap;
    private backstrokeLength;
    private pendingBackstroke;
    private highlightedChoice;
    private sizerElm;
    private sizerElmText;
    private inFocus;
    private prevInputTextLength;
    private shouldUpdateAutoComplete;
    selected: IPickerItem[];
    keepActive: boolean;
    isActive: boolean;
    constructor(container: any, options: ISearchPickerOptions);
    addChoice(item: IPickerItem): void;
    removeChoice(item: IPickerItem): void;
    removeAll(): void;
    getSearchText(): string;
    setSearchText(val: string): void;
    focus(): void;
    getHeight(): any;
    canSelectMoreChoices(): boolean;
    setAutocompleteText(text: string): void;
    removeAutocompleteText(): void;
    private setup();
    private scaleSearchField();
    private ensureSizerElement();
    private bindEvents();
    private onClick();
    private onKeyUp(evt);
    private onInput(evt);
    private onKeyDown(evt);
    private onRemoveChoiceClick(choice);
    private clearHilightedChoice();
    private clearBackstroke();
    private keydownBackstroke();
    private onBlur();
    private onFocus();
    private removeChoiceElement(id);
    private applyTemplate();
    private $renderChoice(item, index);
    private getSelectedChoiceById(id);
    private getChoicesRange(choice1, choice2);
}
